libname a 'D:\EUMC\데이터관리\표본코호트_DB(NHIS_NSC)\JK';

/*계통 추출 방법*/
PROC SURVEYSELECT DATA=A.JK OUT=EXAMPLE METHOD=SYS SAMPSIZE=10000 SEED=54758; 
RUN;

/*층화 추출 방법*/
PROC SORT DATA=A.JK OUT=A.JK2; BY STND_Y AGE_GROUP SIDO; RUN;
PROC SURVEYSELECT DATA=A.JK2 OUT=EXAMPLE2 METHOD=SRS SAMPSIZE=10 SEED=1;
STRATA STND_Y AGE_GROUP ; RUN;
